### ISSUE TITLE
do you have any process in this research?

### ISSUE THREAD

**Issue by dreamcanfly** [theContentMint/GoProRemote#2]
I really want to know how can I let all gopros connect in the same network, because I can't found a device which MAC address is D8:96:85:00:00:00, do you have any suggests?

**Comment by jamiewannenburg** [comment]
Hi dreamcanfly,

I have not made any progress with this project. I do not own a GoPro anymore, so, any further development would be hard for me. When last I tried, I was not able to impersonate a GoPro remote, which would allow all my GoPros to connect to my computer's wifi network. (You might try simply giving your wifi network the correct name.) I could however connect a number of GoPros and my computer to the remote's wifi network, and listen to packets there.

I don't recall MAC addresses being a problem with this setup. So, I don't, unfortunately, have any suggestion for you.

This project was supposed to collect information about the protocol between a remote and GoPros connected to it. It might also be the case that newer GoPros have an entirely different architecture.

**Comment by dreamcanfly** [comment]
jamiewannenburg,

Thank you very much! 
What I need to do now is connecting some Gopros to my computer, and I can send messages(use my soft ware) to all of them so that they can take pictures in the same time. 
you said you have realized this? 

Can you tell me how to reach my goal? And where can I find the protocol btween the Gopro and WIFI-remote?  You write in the article just said it's structure like this:

"The UDP packet has the following form in hex: 00 00 XX 00 00 00 00 Where XX are ASCII characters. The ASCII characters explain what the command is for. Many of the meanings can be gathered from the links above, but there are some new ones."

so do you have the detailed protocal or how can I get it? 

The way I choose is according to this [article:](http://goprohero.readthedocs.io/en/latest/Wifi%20Research/)

P.S.
The reason why I want to know about the MAC address is because I see a document which tell me to change my USB WirelessCard's MAC address to fit the Gopro's OUI, but I can't change my USB card's MAC address. 
I just changed the name of the USB Wireless net's SSID and I found that Gopro can collect it and pair successful, this makes me excited. thank you.

**Comment by jamiewannenburg** [comment]
dreamcanfly,

I did not yet realize your goal of using a computer to trigger multiple Gopros, but that is the ultimate goal of this project. Last I worked on this joshvillbrandt had not yet planned on implementing this feature. His project might now be the right place to implement such a feature. But it does seem that he has not yet fully implemented it (as it is in the wifi research section), so, we might be able to contribute.

Do you have a Gopro remote? If you do, then you should be able to follow the steps in my readme to start collecting raw data about the protocol of the remote. What I know about this protocol is hidden in the `gopro.py` file. I might have a look at this later and try to explain it in words in the readme.

If you look at https://github.com/KonradIT/goprowifihack/blob/master/HERO3/WifiCommands.md there is a list of character pairs and meanings, for example SH means "shutter (open)". The XX in my description refers to this character pair. So, the remote sends such a UPD packet to each camera to tell them to start recording (in video mode) or capture an image (in image mode).

I might be able to get my hands on a Gopro and remote next weekend. We could try to work on this then?

If you are short on time (as I was when I made this) you can use the remote to start recording video on all the cameras and save these timestamps using my program. Then also record the timestamps of whatever you want to trigger the capture on your computer. Then in post, sync the video files (using audio) and capture frames according to the timestamps. I hope this explanation makes sense.

**Comment by KonradIT** [comment]
I have a HERO5 but no remote, a user in my repo said that it was possible to send commands to GoPro H4 cameras with Wifi RC using the Smartphone app commands

**Comment by KonradIT** [comment]
https://github.com/KonradIT/gopro-py-api/issues/10

**Comment by dreamcanfly** [comment]
jamiewannenburg,

I have tried many ways to make all Gopros connect a USB wifi, but I failed, because Gopro can connect the USB wifi but I can‘t found Ip of them(I use windows arp -a, but there do not exist a Ip in it, and I don't know why) so I can't send any messages to them.  so yesterday I changed a wireless router(cisco), and I can get the Gopro's Ip but I have no idea about how to send commands to Gopros, I don't know the port, so I can't send the UDP messages to them, do you have any idea of it.
and when I get all Ips of Gopros, I can use http request to control and set the Gopro as in App mode, but I am afraid this will cause some delay in trigger all camera, because I need to send http url in a loop.
I don't know is there the same delay will come out in the Wifi-remote mode, do you know about it? 
and all I do is the same as @KonradIT mentioned.
if you have any suggest, please tell me. 
Thank you!

**Comment by dreamcanfly** [comment]
KonradIT,

thank you, I can use the way you mentioned to control all the Gopros, it's really helpful.

**Comment by jamiewannenburg** [comment]
@dreamcanfly,

I'm glad you got something to work. I think the looping is unavoidable. I remember that when I did tests using the remote, the delay between captures in the different cameras was too much for my purposes at the time, i.e., to create a freeze frame effect.

**Comment by dreamcanfly** [comment]
@jamiewannenburg 

OK, I found I didn't have to make them take pictures at the same time. 

may I ask you another question? In my test to the Gopros, I found when Gopro camera take pictures, there will be motion blur occured when I was moving. The quality of pictures would be very low and I had to stop and then take a picture, it is very Inefficient. Do you konw any way to make sure Gopro can take good pictures in moving situation? I know that Gopro can get good perfermance at video, but in picture this will be a problem for me.

Thank you very much!  It's really important for me. 
I will close this issue later..

**Comment by KonradIT** [comment]
@dreamcanfly adjust your protune values, what GoPros are you using?

**Comment by dreamcanfly** [comment]
@KonradIT gopro hero 4, gopro's ISO can't be a locked num when take pictures unless I use up limit and low limit to the same value such as 200,400,800.
and if ISO is too high like 800, there will be many hot pixel and the picture's quality is bad.

**Comment by cepoon** [comment]
@dreamcanfly @jamiewannenburg - my goal is to have a travel router acting as a remote control to multiple cameras in a car to record videos from track days.

I just recently picked up my research again (with my Hero 3+ Silver), specifically GoPro WiFi-RC mode. I picked up a travel router last week (TP-Link TL-WR902AC ver 1) which I proceed to load OpenWRT 18.06 onto - that allowed me to "fake" the SSID and MAC to match a GoPro remote. I have been working on a python script and realize that a lot of the commands just matches the commands in GoPro app mode that @KonradIT has discovered for Hero 3 and onwards. The tricky part is integrating all this into the web interface of OpenWRT as right now, you need an SSH session into the router to control the cameras.

For the most part, if you prefer RC mode, the only thing you seem to lose is streaming the video during recording. GoPro app mode has the camera as the WiFi access point, while RC mode has the remote control as the access point. The main problem I see with App mode is the fixed subnet on the camera side which might be problematic for multi-camera operation in this mode. Newer GoPro might have fixed that but with the company not doing so well due to the number of knock-offs at far lower price, I'm not sure it's a good idea to accumulate cameras this late into the GoPro era

If there is a way to coordinate the code for testing I would love to see the results from different versions - in RC mode, if the commands are bad, the camera might do a quick reset so you have to be sure about its capability and send only the acceptable commands

I will clean up the Python script a bit (which has now been ported to micropython since the router don't have much space to run full blown Python 3) before uploading here as I literally just signed up an account to comment here

**Comment by cepoon** [comment]
Also tagging @xuv - I will see how much more time I can spend on this shortly. I have left it for a while and just recently picked up steam again
